<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="NSubstitute" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Revenda.Identity.Domain\Revenda.Identity.Domain.csproj" />
    <ProjectReference Include="..\..\src\Revenda.Identity.Application\Revenda.Identity.Application.csproj" />
  </ItemGroup>

</Project>
